package com.snothin.ghostsam.system

import android.content.Context
import java.io.File
import java.security.MessageDigest

/** Companion APK asset: byte source for injection (--apk signature) and install; generated by
 *  Gradle `syncCompanionApk` - always the same version as the companion sources. */
object CompanionPack {

    const val ASSET = "companion/companion.apk"

    data class Builtin(val file: File, val sha8: String, val versionCode: Long, val versionName: String)

    fun builtin(context: Context): Builtin {
        val (file, sha8) = resolve(context)
        val info = context.packageManager.getPackageArchiveInfo(file.absolutePath, 0)
            ?: error("getPackageArchiveInfo failed: ${file.absolutePath}")
        return Builtin(file, sha8, info.longVersionCode, info.versionName ?: "?")
    }

    fun resolve(context: Context): Pair<File, String> {
        val target = File(context.filesDir, "companion/companion.apk").apply { parentFile?.mkdirs() }
        context.assets.open(ASSET).use { input ->
            target.outputStream().use { output -> input.copyTo(output) }
        }
        val digest = MessageDigest.getInstance("SHA-256").apply {
            target.inputStream().use { stream ->
                val buffer = ByteArray(64 * 1024)
                while (true) {
                    val n = stream.read(buffer)
                    if (n <= 0) break
                    update(buffer, 0, n)
                }
            }
        }.digest().joinToString("") { "%02x".format(it) }.take(8)
        return target to digest
    }
}
